// Code generated by lmn2go from lmn.lmn. DO NOT EDIT.

package highlight

import "github.com/msorc/languagemachine2/lm"

// lmnProgram is the ruleset compiled from lmn.lmn.
var lmnProgram = &lm.Program{
	Name:  "lmn",
	Rules: lmnProgramRules,
	Funcs: map[string]lm.Func{
		"hl": lmHl,
	},
}

const lmnProgramRules = `
m:lmnlight L:0 n:0 ( m:start v:C G f:args d:rule G d:keyword G f:cell d:option G d:keyword G f:cell d:repeat G d:keyword G f:cell d:each G d:keyword G f:cell d:all G d:keyword G f:cell d:var G d:keyword G f:cell d:if G d:keyword G f:cell d:else G d:keyword G f:cell d:for G d:keyword G f:cell d:foreach G d:keyword G f:cell d:while G d:keyword G f:cell d:break G d:keyword G f:cell d:continue G d:keyword G f:cell d:in G d:keyword G f:cell d:null G d:constant G f:cell d:true G d:constant G f:cell d:false G d:constant G f:cell d:start G d:builtin G f:cell d:eof G d:builtin G f:cell d:anything G d:builtin G f:cell d:terminal G d:builtin G f:cell d:nonTerminal G d:builtin G f:cell d:out G d:builtin G f:cell d:err G d:builtin G f:cell d:uri G d:builtin G f:cell d:urd G d:builtin G f:cell d:sp G d:builtin G f:cell d:nl G d:builtin G f:cell d:lineNo G d:builtin G f:cell d:fileName G d:builtin G f:cell d:flagError G d:builtin G f:cell d:warnError G d:builtin G f:cell d:toStr G d:builtin G f:cell d:toLstr G d:builtin G f:cell d:toUstr G d:builtin G f:cell d:toQuote G d:builtin G f:cell d:toSym G d:builtin G f:cell d:toLsym G d:builtin G f:cell d:toUsym G d:builtin G f:cell d:toSys G d:builtin G f:cell d:toLsys G d:builtin G f:cell d:toUsys G d:builtin G f:cell d:toVar G d:builtin G f:cell d:toNum G d:builtin G f:cell d:toOct G d:builtin G f:cell d:toHex G d:builtin G f:cell d:toBin G d:builtin G f:cell d:toUrn G d:builtin G f:cell d:toUrd G d:builtin G f:cell f:array w . ( ( m:bof ) G f:inj ) m:code ) ( m:eof ) r
m:lmnlight L:0 n:0 ( m:eof ) ( m:code m:eof ) r
m:lmnlight L:0 n:1 ( z m:out ) ( m:code ) r
m:lmnlight L:0 n:1 ( m:bof l:%5B%5E%20%5Cn%5D t ( m:repeat l:%5B%5E%5Cn%5D t ) m:toSym v:N p ) ( m:code z v:hl G f:args d:comment G v:N V f:fun f:apply ) r
m:lmnlight L:0 n:1 ( m:bof ) ( m:code ) r
m:lmnlight L:0 n:1 ( c:%5Cn l:%5B%5E%20%5Cn%5D t ( m:repeat l:%5B%5E%5Cn%5D t ) m:toSym v:N p ) ( m:code m:%5Cn z v:hl G f:args d:comment G v:N V f:fun f:apply ) r
m:lmnlight L:0 n:1 ( l:%5BA-Z%5D t ( m:repeat l:%5Ba-zA-Z0-9_%5D t ) m:toSym v:N p ) ( m:code z v:hl G f:args d:variable G v:N V f:fun f:apply ) r
m:lmnlight L:0 n:1 ( l:%5Ba-z_%5D t ( m:repeat l:%5Ba-zA-Z0-9_%5D t ) m:toSym v:N p ) ( m:code z ( v:C V v:N V f:idx ( v:hl G f:args v:C V v:N V f:idx v:N V f:fun f:apply ) G ( v:N V f:apply ) G f:if ) ) r
m:lmnlight L:0 n:1 ( l:%5B0-9%5D t ( m:repeat l:%5B0-9a-zA-Z_.%5D t ) m:toSym v:N p ) ( m:code z v:hl G f:args d:number G v:N V f:fun f:apply ) r
m:lmnlight L:0 n:1 ( c:%3C- ) ( m:code z v:hl G f:args d:operator G d:%3C- G f:fun f:apply ) r
m:lmnlight L:0 n:1 ( c:// t ( m:repeat l:%5B%5E%5Cn%5D t ) m:toSym v:N p ) ( m:code z v:hl G f:args d:comment G v:format G f:args d:/%25s G v:N V f:fun f:fun f:apply ) r
m:lmnlight L:0 n:1 ( c:/* v:B G v:null G w . t v:B V f:append  m:bcmt ) ( m:code z v:hl G f:args d:comment G v:format G f:args d:/%25s G v:B V f:fun f:fun f:apply ) r
m:lmnlight L:0 n:1 ( c:/ t c:* t v:B V f:append  m:bcmt ) ( m:bcmt ) r
m:lmnlight L:0 n:0 ( c:* t c:/ t v:B V f:append  ) ( m:bcmt ) r
m:lmnlight L:0 n:0 ( m:eof ) ( m:bcmt m:eof ) r
m:lmnlight L:0 n:1 ( z m:anything t v:B V f:append  ) ( m:bcmt ) r
m:lmnlight L:0 n:1 ( c:%5C' v:B G v:null G w . t v:B V f:append  m:chars ) ( m:code z v:hl G f:args d:string G v:B V f:fun f:apply ) r
m:lmnlight L:0 n:1 ( c:%5C%5C t m:terminal t v:B V f:append  ) ( m:chars ) r
m:lmnlight L:0 n:0 ( c:%5C' t v:B V f:append  ) ( m:chars ) r
m:lmnlight L:0 n:0 ( c:%5Cn ) ( m:chars c:%5Cn ) r
m:lmnlight L:0 n:0 ( m:eof ) ( m:chars m:eof ) r
m:lmnlight L:0 n:1 ( z l:%5B%5E'%5C%5Cn%5D t v:B V f:append  ) ( m:chars ) r
m:lmnlight L:0 n:1 ( c:%5C%22 v:B G v:null G w . t v:B V f:append  m:sym ) ( m:code z v:hl G f:args d:string G v:B V f:fun f:apply ) r
m:lmnlight L:0 n:1 ( c:%5C%5C t m:terminal t v:B V f:append  ) ( m:sym ) r
m:lmnlight L:0 n:0 ( c:%5C%22 t v:B V f:append  ) ( m:sym ) r
m:lmnlight L:0 n:0 ( c:%5Cn ) ( m:sym c:%5Cn ) r
m:lmnlight L:0 n:0 ( m:eof ) ( m:sym m:eof ) r
m:lmnlight L:0 n:1 ( z l:%5B%5E%22%5C%5Cn%5D t v:B V f:append  ) ( m:sym ) r
m:lmnlight L:0 n:1 ( c:.%5B v:B G v:null G w . t v:B V f:append  m:class ) ( m:code z v:hl G f:args d:regexp G v:format G f:args d:.%25s G v:B V f:fun f:fun f:apply ) r
m:lmnlight L:0 n:1 ( c:%5C%5C t m:terminal t v:B V f:append  ) ( m:class ) r
m:lmnlight L:0 n:0 ( c:%5D t v:B V f:append  ) ( m:class ) r
m:lmnlight L:0 n:0 ( c:%5Cn ) ( m:class c:%5Cn ) r
m:lmnlight L:0 n:0 ( m:eof ) ( m:class m:eof ) r
m:lmnlight L:0 n:1 ( z l:%5B%5E%5D%5C%5Cn%5D t v:B V f:append  ) ( m:class ) r
`
