package lmgo

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"path"
	"strconv"
	"strings"
	"text/template"
	"unicode"

	"github.com/msorc/languagemachine2/internal/machine"
)

// DefaultImport is the import path of the runtime package lm.
const DefaultImport = "github.com/msorc/languagemachine2/lm"

// Config controls the Go code that Generate writes.
type Config struct {
	Package string   // package name; "main" (the default) also writes func main
	Var     string   // name of the Program variable (default Program)
	Name    string   // program name, for messages
	Sources []string // the files the rules came from, for comments
	Prefix  string   // prefix of the Go names of user functions (default lm)
	Import  string   // import path of package lm (default DefaultImport)
}

// Func is a function the rules call that is not a builtin, so the program
// must define it.
type Func struct {
	Name  string // name in the rules
	Ident string // name of the Go function that implements it
}

// Result is what Generate produces.
type Result struct {
	Code    []byte // the generated file
	Funcs   []Func // functions the package must define
	Dynamic int    // calls through an expression, which are bound at run time
}

func (c *Config) defaults() {
	if c.Package == "" {
		c.Package = "main"
	}
	if c.Var == "" {
		c.Var = "Program"
	}
	if c.Prefix == "" {
		c.Prefix = "lm"
	}
	if c.Import == "" {
		c.Import = DefaultImport
	}
}

// Generate writes a Go file that holds rules, which must be .lm bytecode, as
// a Program. The rules are loaded first, so a ruleset that the engine cannot
// load is rejected here and not when the program starts.
func Generate(rules string, cfg Config) (*Result, error) {
	cfg.defaults()
	if !token.IsIdentifier(cfg.Package) || !token.IsIdentifier(cfg.Var) {
		return nil, fmt.Errorf("package %q and variable %q must be Go identifiers", cfg.Package, cfg.Var)
	}
	if err := machine.NewEngine().LoadFromString(rules); err != nil {
		return nil, fmt.Errorf("the rules do not load: %w", err)
	}
	names, dynamic, err := machine.Calls(rules)
	if err != nil {
		return nil, err
	}
	res := &Result{Dynamic: dynamic}
	used := map[string]bool{}
	for _, n := range names {
		if machine.Builtin(n) {
			continue
		}
		res.Funcs = append(res.Funcs, Func{Name: n, Ident: ident(cfg.Prefix, n, used)})
	}

	var buf bytes.Buffer
	err = fileTemplate.Execute(&buf, map[string]any{
		"Cfg":       cfg,
		"Sources":   strings.Join(cfg.Sources, ", "),
		"Funcs":     res.Funcs,
		"Main":      cfg.Package == "main",
		"RulesName": lowerFirst(cfg.Var) + "Rules",
		"Rules":     literal(strip(rules)),
		"Alias":     path.Base(cfg.Import) != "lm",
	})
	if err != nil {
		return nil, err
	}
	if res.Code, err = format.Source(buf.Bytes()); err != nil {
		return nil, fmt.Errorf("formatting the generated code: %w", err)
	}
	return res, nil
}

// Stubs writes a Go file that defines the functions the rules need, for the
// user to fill in.
func Stubs(funcs []Func, cfg Config) ([]byte, error) {
	cfg.defaults()
	var buf bytes.Buffer
	data := map[string]any{"Cfg": cfg, "Funcs": funcs, "Alias": path.Base(cfg.Import) != "lm"}
	if err := stubTemplate.Execute(&buf, data); err != nil {
		return nil, err
	}
	return format.Source(buf.Bytes())
}

// strip drops comment lines, such as a #! header, and blank lines.
func strip(rules string) string {
	var b strings.Builder
	for line := range strings.Lines(rules) {
		t := strings.TrimSpace(line)
		if t == "" || t[0] == '#' {
			continue
		}
		b.WriteString(strings.TrimRight(line, " \t\r\n"))
		b.WriteByte('\n')
	}
	return b.String()
}

// literal quotes rules as a raw string, one rule line per line, or as
// quoted lines when the text cannot be raw.
func literal(s string) string {
	if !strings.ContainsAny(s, "`\r") {
		return "`\n" + s + "`"
	}
	var b strings.Builder
	b.WriteString(`""`)
	for line := range strings.Lines(s) {
		b.WriteString(" +\n\t")
		b.WriteString(strconv.Quote(line))
	}
	return b.String()
}

// ident makes a unique Go identifier for the function name: the prefix
// followed by the name with its first letter upper-cased and anything that
// cannot be in an identifier replaced by _.
func ident(prefix, name string, used map[string]bool) string {
	var b strings.Builder
	b.WriteString(prefix)
	for i, r := range name {
		switch {
		case i == 0 && unicode.IsLetter(r):
			b.WriteRune(unicode.ToUpper(r))
		case unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	id := b.String()
	for n := 2; used[id]; n++ {
		id = fmt.Sprintf("%s%d", b.String(), n)
	}
	used[id] = true
	return id
}

func lowerFirst(s string) string {
	return strings.ToLower(s[:1]) + s[1:]
}

var fileTemplate = template.Must(template.New("file").Parse(`// Code generated by lmn2go{{if .Sources}} from {{.Sources}}{{end}}. DO NOT EDIT.

package {{.Cfg.Package}}

import {{if .Alias}}lm {{end}}"{{.Cfg.Import}}"

// {{.Cfg.Var}} is the ruleset{{if .Sources}} compiled from {{.Sources}}{{end}}.
var {{.Cfg.Var}} = &lm.Program{
	Name:  {{printf "%q" .Cfg.Name}},
	Rules: {{.RulesName}},
{{- if .Funcs}}
	Funcs: map[string]lm.Func{
{{- range .Funcs}}
		{{printf "%q" .Name}}: {{.Ident}},
{{- end}}
	},
{{- end}}
}
{{if .Main}}
func main() { lm.Main({{.Cfg.Var}}) }
{{end}}
const {{.RulesName}} = {{.Rules}}
`))

var stubTemplate = template.Must(template.New("stubs").Parse(`package {{.Cfg.Package}}

import {{if .Alias}}lm {{end}}"{{.Cfg.Import}}"
{{range .Funcs}}
// {{.Ident}} implements {{.Name}}(...) for the rules.
func {{.Ident}}(c *lm.Call) lm.Value {
	// TODO: implement {{.Name}}
	return lm.Null()
}
{{end}}`))
