package lmgo

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestIdent(t *testing.T) {
	t.Parallel()
	used := map[string]bool{}
	for _, c := range []struct{ name, want string }{
		{"shout", "lmShout"},
		{"plus_expr", "lmPlus_expr"},
		{"Shout", "lmShout2"},
		{"a-b", "lmA_b"},
		{"1x", "lm1x"},
	} {
		if got := ident("lm", c.name, used); got != c.want {
			t.Errorf("ident(%q) = %q, want %q", c.name, got, c.want)
		}
	}
}

func TestLiteral(t *testing.T) {
	t.Parallel()
	if got, want := literal("a\nb\n"), "`\na\nb\n`"; got != want {
		t.Errorf("raw: got %q, want %q", got, want)
	}
	if got, want := literal("a`\nb\n"), "\"\" +\n\t\"a`\\n\" +\n\t\"b\\n\""; got != want {
		t.Errorf("quoted: got %q, want %q", got, want)
	}
}

func TestGenerate(t *testing.T) {
	t.Parallel()
	rules, err := Compile("", filepath.Join("testdata", "shout.lmn"))
	if err != nil {
		t.Fatal(err)
	}
	res, err := Generate("#! /usr/bin/lm -r\n"+rules, Config{Package: "shout", Name: "shout", Sources: []string{"shout.lmn"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Funcs) != 2 || res.Funcs[0] != (Func{"count", "lmCount"}) || res.Funcs[1] != (Func{"shout", "lmShout"}) {
		t.Errorf("funcs = %v", res.Funcs)
	}
	code := string(res.Code)
	for _, s := range []string{"// Code generated by lmn2go from shout.lmn. DO NOT EDIT.", "package shout\n", `"shout": lmShout,`, "const programRules = `\nm:shout "} {
		if !strings.Contains(code, s) {
			t.Errorf("generated code lacks %q:\n%s", s, code)
		}
	}
	if strings.Contains(code, "func main") || strings.Contains(code, "#!") {
		t.Errorf("library code has func main or the #! header:\n%s", code)
	}
	if _, err := Generate("m:t L:0 n:0 ( z v:X T ) ( m:eof ) r\n", Config{}); err == nil {
		t.Error("rules that do not load: no error")
	}
}

// The generated code must build outside this module, as a user's program
// would, and behave as the lm command does with the same rules.
func TestGeneratedProgram(t *testing.T) {
	if testing.Short() {
		t.Skip("builds Go programs")
	}
	t.Parallel()
	goTool, err := exec.LookPath("go")
	if err != nil {
		t.Skip("no go command")
	}
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	build := func(t *testing.T, name string, files map[string]string) string {
		dir := t.TempDir()
		files["go.mod"] = "module " + name + "\n\ngo 1.27\n\nrequire github.com/msorc/languagemachine2 v0.0.0\n\nreplace github.com/msorc/languagemachine2 => " + root + "\n"
		for f, text := range files {
			if err := os.WriteFile(filepath.Join(dir, f), []byte(text), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		bin := filepath.Join(dir, name)
		cmd := exec.Command(goTool, "build", "-mod=mod", "-o", bin, ".")
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GOPROXY=off", "GOFLAGS=", "GOWORK=off")
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("go build: %v\n%s\n%s", err, out, files[name+".go"])
		}
		return bin
	}
	generate := func(t *testing.T, src string) (*Result, Config) {
		rules, err := Compile("", src)
		if err != nil {
			t.Fatal(err)
		}
		cfg := Config{Name: filepath.Base(src), Sources: []string{filepath.Base(src)}}
		res, err := Generate(rules, cfg)
		if err != nil {
			t.Fatal(err)
		}
		return res, cfg
	}

	t.Run("flatten", func(t *testing.T) {
		t.Parallel()
		examples := filepath.Join(root, "examples", "samples")
		res, _ := generate(t, filepath.Join(examples, "flatten.lmn"))
		bin := build(t, "flatten", map[string]string{"flatten.go": string(res.Code)})
		got, err := exec.Command(bin, filepath.Join(examples, "flatten.input")).Output()
		if err != nil {
			t.Fatal(err)
		}
		if want, _ := os.ReadFile(filepath.Join(examples, "flatten.flat")); string(got) != string(want) {
			t.Errorf("output differs from flatten.flat:\n%s", got)
		}
	})

	t.Run("funcs", func(t *testing.T) {
		t.Parallel()
		res, cfg := generate(t, filepath.Join("testdata", "shout.lmn"))
		stubs, err := Stubs(res.Funcs, cfg)
		if err != nil {
			t.Fatal(err)
		}
		// the stubs build as they are; replace them with implementations
		build(t, "stubs", map[string]string{"shout.go": string(res.Code), "funcs.go": string(stubs)})
		funcs := `package main

import (
	"strings"

	"github.com/msorc/languagemachine2/lm"
)

func lmShout(c *lm.Call) lm.Value { return lm.Sym(strings.ToUpper(c.Arg(0).String()) + "!") }

func lmCount(c *lm.Call) lm.Value { return lm.Num(float64(len(c.Args))) }
`
		bin := build(t, "shout", map[string]string{"shout.go": string(res.Code), "funcs.go": funcs})
		got, err := exec.Command(bin, "-input", "a!b#c").Output()
		if err != nil {
			t.Fatal(err)
		}
		if want := "aHEY!b3c"; string(got) != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})
}
